apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-app  
  name: hello-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-app
  sessionAffinity: None
  type: LoadBalancer
